In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_excel("Flowers-Train.xlsx")

In [3]:
data

,sepal length in cm,sepal width in cm,sepal length in cm,petal width in cm,Class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,7.9,3.8,1.4,2.0,Iris-virginica
2,7.7,3.8,1.4,2.2,Iris-virginica
3,7.7,2.8,1.4,2.0,Iris-virginica
4,7.6,3.0,1.4,2.1,Iris-virginica
...,...,...,...,...,...
145,4.5,2.3,1.4,0.3,Iris-setosa
146,4.4,3.2,1.4,0.2,Iris-setosa
147,4.4,3.0,1.4,0.2,Iris-setosa
148,4.4,2.9,1.4,0.2,Iris-setosa
149,4.3,3.0,1.4,0.1,Iris-setosa

In [4]:
data.head()

,sepal length in cm,sepal width in cm,sepal length in cm,petal width in cm,Class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,7.9,3.8,1.4,2.0,Iris-virginica
2,7.7,3.8,1.4,2.2,Iris-virginica
3,7.7,2.8,1.4,2.0,Iris-virginica
4,7.6,3.0,1.4,2.1,Iris-virginica

In [5]:
data_Test = pd.read_excel("Flowers-Test.xlsx")

In [6]:
data_Test.head()

,sepal length in cm,sepal width in cm,sepal length in cm,petal width in cm,Class
0,6.2,2.9,1.4,1.3,Iris-virginica
1,6.2,2.8,1.4,1.8,Iris-virginica
2,6.2,2.2,1.4,1.5,Iris-virginica
3,6.1,3.0,1.4,1.8,Iris-virginica
4,6.1,3.0,1.4,1.4,Iris-virginica

### We select All Coumns except last one

In [7]:
x = data.iloc[:,:-1]

In [8]:
x

,sepal length in cm,sepal width in cm,sepal length in cm,petal width in cm
0,5.1,3.5,1.4,0.2
1,7.9,3.8,1.4,2.0
2,7.7,3.8,1.4,2.2
3,7.7,2.8,1.4,2.0
4,7.6,3.0,1.4,2.1
...,...,...,...,...
145,4.5,2.3,1.4,0.3
146,4.4,3.2,1.4,0.2
147,4.4,3.0,1.4,0.2
148,4.4,2.9,1.4,0.2
149,4.3,3.0,1.4,0.1

### Select Last Row

In [9]:
y = data.iloc[:,4]

In [10]:
y

0         Iris-setosa
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
145       Iris-setosa
146       Iris-setosa
147       Iris-setosa
148       Iris-setosa
149       Iris-setosa
Name: Class, Length: 150, dtype: object

In [11]:
model = RandomForestClassifier()

In [12]:
model.fit(x.values,y.values)

RandomForestClassifier()

In [13]:
prediction = model.predict([[6.1,	2.6	,1.4,	1.4
]])

In [14]:
prediction

array(['Iris-versicolor'], dtype=object)

In [15]:
x_test = data_Test.iloc[:,:-1]

In [16]:
Test_Prediction = model.predict(x_test.values)

In [17]:
Test_Prediction

array(['Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [18]:
y_test = data_Test.iloc[:,-1]

In [19]:
actual = y_test.values

In [21]:
count = 0 
for i in range(0, len(actual)):
    if actual[i]== Test_Prediction[i]:
        count = count+1
print(count/ len(actual)*100)

100.0